export const oliveBlank = () => {
	const oliveBlanks = [
		{ id: 'mab1', content: `Get roasted`, timer: false },
		{ id: 'mab4', content: 'Bare your teeth', timer: false },
		{ id: 'mab5', content: 'Whistle a quick melody', timer: false },
		{ id: 'mab7', content: 'Moan', timer: false },
		{ id: 'mab8', content: 'Sing your favourite song', timer: false },
		{ id: 'mab9', content: 'Mumble rap', timer: false },
		{ id: 'mab10', content: 'Scream', timer: false },
		{ id: 'mab11', content: 'Make fart sounds', timer: false },
		{ id: 'mab12', content: 'Make chicken sounds', timer: false },
		{ id: 'mab13', content: 'Bark like a dog', timer: false },
		{ id: 'mab14', content: 'Yell at your phone', timer: false },
		{ id: 'mab15', content: 'Meow like a cat', timer: false },
		{ id: 'mab16', content: 'Breathe like a dog with your tongue out', timer: false },
		{ id: 'mab19', content: 'Yodel from the heart', timer: false },
		{ id: 'mab20', content: 'Cry tears of joy', timer: false },
		{ id: 'mab21', content: 'Trash talk', timer: false },
		{ id: 'mab22', content: 'Groan like you have stepped on a lego', timer: false },
		{ id: 'mab25', content: 'Aregue with your belly', timer: false },
		{ id: 'mab26', content: 'Unravel the meaning of life', timer: false },
		{ id: 'mab27', content: 'Carol a verse of "Jingle Bells"', timer: false },
		{ id: 'mab29', content: 'Play an imaginary trumpet', timer: false },
		{ id: 'mab37', content: 'Pray like the world is about to end', timer: false },
		{ id: 'mab42', content: 'Voice-over the current scene', timer: false },
		{ id: 'mab45', content: 'Preach like you are the shit', timer: false },
		{ id: 'mab47', content: 'Apologise for being so humble', timer: false },
		{ id: 'mab49', content: 'Convince everyone oxygen is bad for you', timer: false },
		{ id: 'mab50', content: 'Express your love for crossaints in a french accent', timer: false },
		{ id: 'mab53', content: 'Describe how much you love yourself', timer: false },
		{ id: 'mab54', content: 'Reasure your co-players you are not in a blackout right now', timer: false },
		{ id: 'mab56', content: 'Entice a wall to go out with you', timer: false },
		{ id: 'mab58', content: 'Sweet-talk to your drink', timer: false },
		{ id: 'mab59', content: 'Brag about your sick lifestyle', timer: false },
		{ id: 'mab65', content: 'Perform a sweet serenade', timer: false },
		{ id: 'mab67', content: 'Make a fuss of the Tooth Fairy scam', timer: false },
		{ id: 'mab68', content: 'Raise a witty toast', timer: false },
		{ id: 'mab70', content: 'Give your best excuse to leave early', timer: false },
		{ id: 'mab72', content: 'Give out a backhanded compliment', timer: false },
		{ id: 'mab75', content: 'Tell a dad joke', timer: false },
		{ id: 'mab77', content: 'Comment everyones choice of drink', timer: false },
		{ id: 'mab78', content: 'Mention how smart you are', timer: false },
		{ id: 'mab79', content: 'Bat around your daddy issues', timer: false },
		{ id: 'mab80', content: 'Verbally attack a frying pan', timer: false },
		{ id: 'mab85', content: 'Beg for mercy', timer: false },
		{ id: 'mab86', content: 'Report on the current state of the party', timer: false },
		{ id: 'mab90', content: 'Prove you are not a flat-earther', timer: false },
		{ id: 'mab91', content: 'Narrate your gameplay in third person', timer: false },
		{ id: 'mab92', content: 'Aggresively describe how to make toast', timer: false },
		{ id: 'mab97', content: 'Rehearse your pick-up lines', timer: false },
	
	];
	const randomWordIndex = Math.floor(Math.random() * oliveBlanks.length) + 0;
	const challenge = oliveBlanks[randomWordIndex];
	return challenge;
};

// 'Roast other players for 30 seconds',
//     'Curse every 3 seconds',
//     'Offer everyone shots for 10 seconds',
//     'Try selling your clothes to other players for 10 seconds',
//     'Giggle for 5 seconds',
//     'Whistle for 10 seconds',
//     'Whisper for 10 seconds',
//     'Moan for 10 seconds',
//     'Sing for 30 seconds',
//     'Rap for 30 seconds',
//     'Scream for 5 seconds',
//     'Improvise a presentation for 1 minute',
//     'Get roasted for 1 minute',
//     'Make fart sounds for 10 seconds',
//     'Make chicken sounds for 10 seconds',
//     'Bark like a dog for 10 seconds',
//     'Yell at everyone for 10 seconds',
//     'Meow like a cat for 10 seconds',
//     'Stick your tongue out and breathe like a dog for 10 seconds',
