export const martiniCard = (blank) => {
	const martiniCards = [
		{
			id: 'mac1',
			blankId: blank.id,
			title: `Sleep Talk`,
			content: `Lay down on the ground and ${blank.content} as you pretend to be asleep.`,
			comment: `You do this every night regardless.`,
			timer: false,
		},
		{
			id: 'mac2',
			blankId: blank.id,
			title: `Grenade Serenade`,
			content: `Gaze at the player to your right and ${blank.content} as if you’re trying to flirt.`,
			comment: `Don’t try this in public.`,
			timer: false,
		},
		{
			id: 'mac3',
			blankId: blank.id,
			title: `Double Stacked`,
			content: `Choose a player and ${blank.content} as you sit on their lap.`,
			comment: `Just embrace the awkwardness.`,
			timer: false,
		},
		{
			id: 'mac4',
			blankId: blank.id,
			title: `Sweaty Palms`,
			content: `Choose two players and ${blank.content} as you hold their hands.`,
			comment: `Don't be shy.`,
			timer: false,
		},
		{
			id: 'mac5',
			blankId: blank.id,
			title: `Dead Arm`,
			content: `Arm-wrestle every player in the room and ${blank.content} for each defeat.`,
			comment: `Show them how it's done.`,
			timer: false,
		},
		{
			id: 'mac6',
			blankId: blank.id,
			title: `Wonky Ass`,
			content: `${blank.content} as you stand on one leg.`,
			comment: `Keep it cool.`,
			timer: false,
		},
		{
			id: 'mac7',
			blankId: blank.id,
			title: `Morsel Toss`,
			content: `${blank.content} and catch a small piece of food as you throw it in the air.`,
			comment: `Drop the 5 second rule.`,
			timer: false,
		},
		{
			id: 'mac8',
			blankId: blank.id,
			title: `Rock-Paper-Scissors`,
			content: `Play ‘Rock-Paper-Scissors’ with each one of your co-players and ${blank.content} every time you lose.`,
			comment: `Beat the odds.`,
			timer: false,
		},
		{
			id: 'mac9',
			blankId: blank.id,
			title: `Piggyback`,
			content: `Give a quick piggyback ride to one of the players and ${blank.content} as you carry them around.`,
			comment: `Oink oink.`,
			timer: false,
		},
		{
			id: 'mac10',
			blankId: blank.id,
			title: `Heads & Tails`,
			content: `Get a coin and toss it. If it lands on heads ${blank.content} alone, if it lands on tails pick someone to do it with you.`,
			comment: `Feeling lucky today?`,
			timer: false,
		},
		{
			id: 'mac11',
			blankId: blank.id,
			title: `Free Kick`,
			content: `Flick a small paper ball through a goalpost made by the player sitting across and ${blank.content} every time you miss.`,
			comment: `It’s football, not football.`,
			timer: false,
		},
		{
			id: 'mac12',
			blankId: blank.id,
			title: `Locked Out`,
			content: `Exit the room and ${blank.content} behind the door.`,
			comment: `Hope no one locks you out.`,
			timer: false,
		},
		{
			id: 'mac13',
			blankId: blank.id,
			title: `Tic-Tac-Toe`,
			content: `Play Tic-Tac-Toe with a player to your right and ${blank.content} if you end up in a tie or lose.`,
			comment: `X's and O's.`,
			timer: false,
		},
		{
			id: 'mac14',
			blankId: blank.id,
			title: `Broken Telephone`,
			content: `Whisper a two-sentance story to a player on your left and they must do the same until it comes back to you. ${blank.content} if the story changed.`,
			comment: `Walkie Talkie.`,
			timer: false,
		},
		{
			id: 'mac15',
			blankId: blank.id,
			title: `Sleep Walk`,
			content: `Close your eyes and ${blank.content} as you walk around the room.`,
			comment: `No peeking.`,
			timer: false,
		},
		{
			id: 'mac16',
			blankId: blank.id,
			title: `Moon Landing`,
			content: `Put a bowl over your head and ${blank.content} as you act out the moon landing.`,
			comment: `It’s a small step for you and an even smaller one for humanity.`,
			timer: false,
		},
		{
			id: 'mac17',
			blankId: blank.id,
			title: `Turn-Off`,
			content: `Get into your favourite sex position and ${blank.content}.`,
			comment: `That is your mission(ary).`,
			timer: false,
		},
		{
			id: 'mac18',
			blankId: blank.id,
			title: `Limpy Simp`,
			content: `Kneel in front of the player to your right and ${blank.content}.`,
			comment: `Don't worry, they arn't proposing.`,
			timer: false,
		},
		{
			id: 'mac19',
			blankId: blank.id,
			title: `Arch of Pain`,
			content: `${blank.content} as you arch back and meet the ground.`,
			comment: `Without breaking your back.`,
			timer: false,
		},
		{
			id: 'mac20',
			blankId: blank.id,
			title: `Time Out`,
			content: `Sit in a corner of the room facing the wall and ${blank.content}.`,
			comment: `Don't be sad.`
		},
	];
	const randomWordIndex = Math.floor(Math.random() * martiniCards.length) + 0;
	const challenge = martiniCards[randomWordIndex];
	return challenge;
};

// `(Bystander) Everyone must ${blank} together, except you. Enjoy the show.`,
//     `(Off the Cuff) The last player to stand up must ${blank}. Blame the game.`,
//     `(Grenade Serenade) Flirtatiously gaze at the player to your right and ${blank}. Don’t try this in public.`,
//     `(Double Stacked) Choose a player and ${blank} as you sit on their lap. Just embrace the awkwardness.`,
//     `(Sweaty palms) Choose two players and ${blank} as you hold their hands. You won’t need them now anyway.`,
//     `(Gorilla Grip) Arm-wrestle every player in the room and ${blank} for each defeat. Do you even lift?`,
//     `(Flamingo) Stand on one leg and ${blank}. It’s just you vs gravity.`,
//     `(Limboo!) Everyone play limbo. The first player to stumble must ${blank} after everyone is finished. Don't forget the music!`,
//     `(Kitchen Master) Throw a small piece of food in the air and catch it using a spoon. ${blank} after you catch it without dropping the piece. Don’t say it’s the shaky hands again.`,
//     `(Rock-Paper-Scissors) Play ‘Rock-Paper-Scissors’ with every player and ${blank} every time you get wrecked. —-----------`,
//     `() Each player must pretend to slap you at one point during the game. ${blank} every time you flinch. _______`,
//     `(Red Hands) Play “Red Hands” (the hand slapping game) with each player. Yours are always on top, unfortunately. ${blank} each time you get slapped or pull your hands away too early.`,
//     `(Piggy Ride) Give a quick piggy back-ride to the player on your left and ${blank} as you carry them around. No bumps in your path, don’t worry.`,
//     `(Heads or Tails) Get a coin and toss it. If it lands on heads ${blank} alone, if it lands on tails pick someone to do it with you. Feeling lucky today?`,
//     `(Free Kick) Flick a small paper ball through a goalpost made by the player sitting across and ${blank} every time you miss. It’s football, not football.`,
//     `(Jazzercise) ${blank} and do jumping jacks as if you’re leading an aerobics class. Don’t forget the hips.`,
//     `(On the Mat) Exit the room and ${blank} behind the door. Hope no one locks you out.`,
//     `(Tic-Tac-Toe) Play Tic-Tac-Toe with a player to your right and ${blank} if you end up in a tie or lose. Xs and Os don’t land on your nose.`,
//     `(Broken Telephone) Whisper a two-sentance story to a player on your left and they must do the same until it comes back to you. ${blank} if the story changed.`,
