export const whiskeyCard = (blank) => {
	const whiskeyCards = [
		{
			id: 'whc1',
			blankId: blank.id,
			title: `Class Clown`,
			content: `${blank.content} and make at least one player laugh.`,
			comment: `Easy, right?`,
			timer: false,
		},
		{
			id: 'whc2',
			blankId: blank.id,
			title: `Poker Face`,
			content: `Keep a poker face and ${blank.content}.`,
			comment: `Just like you practised.`,
			timer: false,
		},
		{
			id: 'whc3',
			blankId: blank.id,
			title: `M.C. Hammer`,
			content: `${blank.content} as you say "Can't touch this".`,
			comment: `Stop, Hammer time.`,
			timer: false,
		},
		{
			id: 'whc4',
			blankId: blank.id,
			title: `Flash Back`,
			content: `Get your hands tied up behind your back and ${blank.content}.`,
			comment: `Don't act like it's your first time.`,
			timer: false,
		},
		{
			id: 'whc5',
			blankId: blank.id,
			title: `Sniper`,
			content: `Place a cup at the opposite end of the table. Then, try to throw a small item into it and ${blank.content} after each shot until you make it.`,
			comment: `Thought those ‘Beer Pong’ nights won’t ever pay off?`,
			timer: false,
		},
		{
			id: 'whc6',
			blankId: blank.id,
			title: `Chicken Legs`,
			content: `Crouch-walk around the room and ${blank.content} in each corner.`,
			comment: `For all the leg days you skipped.`,
			timer: false,
		},
		{
			id: 'whc7',
			blankId: blank.id,
			title: `Mama's boy`,
			content: `${blank.content} and shout mom for help.`,
			comment: `Unfortunately, it's all on you now.`,
			timer: false,
		},
		{
			id: 'whc8',
			blankId: blank.id,
			title: `Patriot`,
			content: `${blank.content} and sing your National anthem as loud as you can.`,
			comment: `You know the words right?`,
			timer: false,
		},
		{
			id: 'whc9',
			blankId: blank.id,
			title: `Soaked`,
			content: ` ${blank.content} and down a glass of water.`,
			comment: `Stay hydrated.`,
			timer: false,
		},
		{
			id: 'whc10',
			blankId: blank.id,
			title: `Minute of Silence`,
			content: `${blank.content} and do a 360° without making a sound.`,
			comment: `Keep it down.`,
			timer: false,
		},
		{
			id: 'whc11',
			blankId: blank.id,
			title: `Snack Time`,
			content: `${blank.content} and try to land a piece of food in your mouth as the player across throws it.`,
			comment: `Just without making a total mess around, right?`,
			timer: false,
		},
		{
			id: 'whc12',
			blankId: blank.id,
			title: `Elevator Pitch`,
			content: `Describe your love for “Topped Off” and ${blank.content} as you’re doing so.`,
			comment: `Make a demo they won’t forget.`,
			timer: false,
		},
		{
			id: 'whc13',
			blankId: blank.id,
			title: `Macarena`,
			content: `Do the macarena until the song ends and ${blank.content} after every “Ayyyy Macarena!”.`,
			comment: `You love this song, don’t you?`,
			timer: false,
		},
		{
			id: 'whc14',
			blankId: blank.id,
			title: `Sunday Roast`,
			content: `${blank.content} and roast other players.`,
			comment: `Take it easy, ok?`,
			timer: false,
		},
		{
			id: 'whc15',
			blankId: blank.id,
			title: `Naked Truth`,
			content: `${blank.content} as you reveal a fun fat about yourself.`,
			comment: `Spill the beans.`,
			timer: false,
		},
		{
			id: 'whc16',
			blankId: blank.id,
			title: `Stuntman`,
			content: `Do a cartwheel and ${blank.content} as soon as you land.`,
			comment: `No one’s a natural.`,
			timer: false,
		},
		{
			id: 'whc17',
			blankId: blank.id,
			title: `Shot in the dark`,
			content: `Close your eyes and describe everyone’s eye color. Also, ${blank.content} every time you get it wrong.`,
			comment: `Trust your gut… or memory.`,
			timer: false,
		},
		{
			id: 'whc18',
			blankId: blank.id,
			title: `Thumb War`,
			content: `Challenge each player to a thumb war and ${blank.content} each time you lose.`,
			comment: `One thumb to rule them all.`,
			timer: false,
		},
		{
			id: 'whc19',
			blankId: blank.id,
			title: `Plot Twist`,
			content: `Choose a topic and let the group build a sentence word by word. Repeat the exact sentence ${blank.content}.`,
			comment: `Shoot your shot or take a shot.`,
			timer: false,
		},
		{
			id: 'whc20',
			blankId: blank.id,
			title: `Silverflip`,
			content: `Flip a spoon into a glass and ${blank.content} everytime you miss.`,
			comment: `Little spoon or big spoon, doesn’t matter this time.`,
			timer: false,
		},
	];
	const randomWordIndex = Math.floor(Math.random() * whiskeyCards.length) + 0;
	const challenge = whiskeyCards[randomWordIndex];
	return challenge;
};
