export const whiskeyCard = (blank) => {
  const whiskeyCards = [
    {
      title: `Class Clown`,
      content: `${blank} and make at least one player laugh.`,
      comment: `Easy, right?`,
      timer: false,
    },
    {
      title: `Poker Face`,
      content: `Keep a poker face and ${blank}.`,
      comment: `Let’s hope all the flies on the wall stay silent.`,
      timer: false,
    },
    {
      title: `Shit Show`,
      content: `${blank} as if it’s a part of your stand-up because every player you crack up takes a drink.`,
      comment: `Hope no one’s filming`,
      timer: false,
    },
    {
      title: `Flash Back`,
      content: `Get your hands tied up behind your back and ${blank}.`,
      comment: ``,
      timer: false,
    },
    {
      title: `Sniper`,
      content: `Place a cup at the opposite end of the table and try to throw a small item into it. ${blank} after each shot until you make it.`,
      comment: `Thought those ‘Beer Pong’ nights won’t ever pay off?`,
      timer: false,
    },
    {
      title: `Chicken Legs`,
      content: `Crouch-walk around the room and ${blank} in each corner.`,
      comment: `For all the leg days you skipped.`,
      timer: false,
    },
    {
      title: `Ready Steady`,
      content: `Keep one leg off the ground and ${blank}.`,
      comment: `There’s no way you took too much to mess this up.`,
      timer: false,
    },
    {
      title: `Patriot`,
      content: `${blank} and sing your National anthem as loud as you can.`,
      comment: `You know the words right?`,
      timer: false,
    },
    {
      title: `Soaked`,
      content: ` ${blank} and take a shot/sip of your drink.`,
      comment: `Stay hydrated.`,
      timer: false,
    },
    {
      title: `Minute of Silence`,
      content: `${blank} and do a 360° without making a sound.`,
      comment: `Keep it down.`,
      timer: false,
    },
    {
      title: `Snack Time`,
      content: `${blank} and try to land a piece of food in your mouth as the player across throws it.`,
      comment: `Just without making a total mess around, right?`,
      timer: false,
    },
    {
      title: `Elevator Pitch`,
      content: `Convince other players to buy “Topped Off” and ${blank} as you’re doing so.`,
      comment: `Make a demo they won’t forget.`,
      timer: false,
    },
    {
      title: `Macarena`,
      content: `Do the macarena until the song ends and ${blank} after every “Ayyyy Macarena!”.`,
      comment: `You love this song, don’t you?`,
      timer: false,
    },
    {
      title: `Bar Special`,
      content: `Choose a player to make you a funky cocktail. ${blank} as you're drinking it.`,
      comment: `Bottoms up!`,
      timer: false,
    },
    {
      title: `Back to School`,
      content: `Give every player a nickname. ${blank} after you drop one.`,
      comment: `Go easy on them ok?`,
      timer: false,
    },
    {
      title: `Stuntman`,
      content: `Do a cartwheel and ${blank} as soon as you land.`,
      comment: `No one’s a natural.`,
      timer: false,
    },
    {
      title: `Shot in the dark`,
      content: `Close your eyes and describe everyone’s eye color. ${blank} each time you get it wrong.`,
      comment: `Trust your gut… or memory.`,
      timer: false,
    },
    {
      title: `Thumb War`,
      content: `Challenge each player to a thumb war and ${blank} each time you lose.`,
      comment: `One thumb to rule them all.`,
      timer: false,
    },
    {
      title: `Plot Twist`,
      content: `Choose a topic and let the group build a sentence word by word. ${blank} and repeat the exact sentence.`,
      comment: `Shoot your shot or take a shot.`,
      timer: false,
    },
    {
      title: `Flip Off/Front Flip/Hardflip`,
      content: `Flip a spoon into a glass and ${blank} everytime you miss.`,
      comment: `Little spoon or big spoon, doesn’t matter this time.`,
      timer: false,
    },
    {
      title: `One Small Step for Man`,
      content: `Moonwalk around the table and ${blank}`,
      comment: `MJ would be proud.`,
      timer: false,
    },
  ];
  const randomWordIndex = Math.floor(Math.random() * whiskeyCards.length) + 0;
  const challenge = whiskeyCards[randomWordIndex];
  return challenge;
};

// `(Class Clown) ${blank} and make at least one player laugh. Easy, right?`,
//     `(Poker Face) Keep a poker face and ${blank}. Let’s hope all the flies on the wall stay silent.`,
//     `(Shit Show) ${blank} as if it’s a part of your stand-up because every player you crack up takes a drink. Hope no one’s filming.`,
//     `(Flash Back) Get your hands tied up behind your back and ${blank}. Don’t act like it’s your first time.`,
//     `(Sniper) Place a cup at the opposite end of the table and try to throw a small item into it. ${blank} after each shot until you make it. Thought those ‘Beer Pong’ nights won’t ever pay off?`,
//     `(Chicken Legs) Crouch-walk around the room and ${blank} in each corner. For all the leg days you skipped.`,
//     `(Ready Steady) Keep one leg off the ground and ${blank}.  There’s no way you took too much to mess this up.`,
//     `(Patriot) ${blank} and sing your National anthem as loud as you can. You know the words right?`,
//     `(Soaked) ${blank} and take a shot/sip of your drink. Stay hydrated.`,
//     `(Minute of Silence) ${blank} and do a 360° without making a sound. Keep it down.`,
//     `(Snack Time) ${blank} and try to land a piece of food in your mouth as the player across throws it. Just without making a total mess around, right?`,
//     `(Elevator Pitch) Convince other players to buy “Topped Off” and ${blank} as you’re doing so. Make a demo they won’t forget.`,
//     `(Macarena) Do the macarena until the song ends and ${blank} after every “Ayyyy Macarena!”. You love this song, don’t you?`,
//     `(Bar Special) Choose a player to make you a funky cocktail. ${blank} as you're drinking it. Bottoms up!`,
//     `(Back to School) Give every player a nickname. ${blank} after you drop one. Go easy on them ok?`,
//     `(Stuntman) Do a cartwheel and ${blank} as soon as you land. No one’s a natural.`,
//     `(Shot in the dark) Close your eyes and describe everyone’s eye color. ${blank} each time you get it wrong. Trust your gut… or memory.`,
//     `(Thumb War) Challenge each player to a thumb war and ${blank} each time you lose. One thumb to rule them all.`,
//     `(Plot Twist) Choose a topic and let the group build a sentence word by word. ${blank} and repeat the exact sentence. Shoot your shot or take a shot.`,
//     `(Flip Off/Front Flip/Hardflip) Flip a spoon into a glass and ${blank} everytime you miss. Little spoon or big spoon, doesn’t matter this time.`,
//     `Moonwalk around the table and ${blank}`,
